language: node_js
node_js:
  - 8.9.1
sudo: false
notifications:
  slack: gambitechno:edLQSSlj2SRDMpLqzVy89oYp
services:
  - redis-server
cache:
  directories:
    - "node_modules"
before_install:
  - cp .env.example .env
install:
  - npm install